CREATE DATABASE IF NOT EXISTS DBUI;
USE DBUI;
drop table organizations;
CREATE TABLE IF NOT EXISTS users(
    userId INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    userName VARCHAR(255) NOT NULL,
    userPassword VARCHAR(255) NOT NULL,
    age INT,
    admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS organizations (
	orgId serial PRIMARY KEY,
	orgName VARCHAR ( 128 ) UNIQUE NOT NULL,
	totalBudget REAL NOT NULL,
	budgetId INT
);